### ISSUE TITLE
Error while launching the bars

### ISSUE THREAD

**Issue by F4zii** [Yucklys/polybar-nord-theme#6] opened 2020-09-16 20:56 UTC
While running `./launch.sh`
```
iddos@iddo-pc polybar $ ./launch.sh dark
Bars launched...
error: Monitor "eDP-1" not found or disconnected
error: Monitor "eDP-1" not found or disconnected```
```
I have 2 monitors, might be the cause of the problem, I hope you guys can help me out here

**Comment by Yucklys** [comment] 2020-09-17 06:38
This is because the monitor is not set correctly for your device. You can have a look at the **monitor** keyword in [bar settings](https://github.com/polybar/polybar/wiki/Configuration#bar-settings) .

You need to find out the the code for your monitor by `polybar -m | cut -d ':' -f 1` or `xrandr -q | grep " connected" | cut -d ' ' -f1`, and replace default `moniter` keyword in `nord-config`.

If you want to customize further more (e.g. display polybar on all monitor), you can look at the document of polybar and config at your preference.

**Comment by F4zii** [comment] 2020-09-17 06:47
What  are the bars name in this theme? i thought about using

```
for m in $(polybar --list-monitors | cut -d":" -f1); do
    MONITOR=$m polybar --reload example &
done
```

but I couldnt find the bar name to replace with `example`

**Comment by Yucklys** [comment] 2020-09-17 06:51
Bar names are nord-top and nord-down for top bar and bottom bar. You should also include `-c [Path to dark/light config]` to choose the correct theme. You can look at the example in `launch.sh`.

**Comment by F4zii** [comment] 2020-09-17 07:11
I tried
```
# Launch bar1 and bar2
if [ "$1" == "light" ]
then
        for m in $(polybar --list-monitors | cut -d":" -f1); do
          MONITOR=$m polybar --reload -c $HOME/.config/polybar/light-config nord-top &
          MONITOR=$m polybar --reload -c $HOME/.config/polybar/light-config nord-down &
        done
 
        # polybar -c $HOME/.config/polybar/light-config nord-top &
        # polybar -c $HOME/.config/polybar/light-config nord-down &
else
        
        for m in $(polybar --list-monitors | cut -d":" -f1); do
          MONITOR=$m polybar --reload -c $HOME/.config/polybar/dark-config nord-top &
          MONITOR=$m polybar --reload -c $HOME/.config/polybar/dark-config nord-down &
        done

        # polybar -c $HOME/.config/polybar/dark-config nord-top &
        # polybar -c $HOME/.config/polybar/dark-config nord-down &
fi

echo "Bars launched..."

```

Bars are now launching on both screens but im getting a lot of errors, also the scale of the bars are messed up
![ss](https://user-images.githubusercontent.com/44242259/93432337-12c3e180-f8ce-11ea-9829-0816b5ce3e79.png)
```
error: Disabling module "bspwm" (reason: Could not find socket: /tmp/bspwm_0_0-socket)
error: module/mpd: Connection refused
error: Disabling module "bspwm" (reason: Could not find socket: /tmp/bspwm_0_0-socket)
error: module/mpd: Connection refused
error: Disabling module "network-short" (reason: Invalid network interface "wlp59s0")
error: Disabling module "battery" (reason: No suitable way to get current charge state)
error: module/mpd: Connection refused
error: Disabling module "network-short" (reason: Invalid network interface "wlp59s0")
error: Disabling module "battery" (reason: No suitable way to get current charge state)
error: module/mpd: Connection refused
error: Failed to restack bar window
```

**Comment by F4zii** [comment] 2020-09-17 07:28
I will install the optional dependencies to clear some errors out, but I still have some problems with mpd and the characters for some reason.

**Comment by Yucklys** [comment] 2020-09-17 07:34
The mess outputs are due to the missing font. I use WenQuanYiMicroHei as default font. You can try install it or change it to another font in `dark-config/light-config`.

The errors are caused by incapable settings.
- For `bspwm`, this module should only enabled for bspwm user. If you are using i3 wm, replace this one with `i3` in `nord-config`.
- For `mpd`, if you don't use mpd, just delete it from module list in `nord-config`. If you customized the server host or port, change `mpd-host` and `mpd-port` to yours in `nord-config`.
- For `network-short`, check your network-interface by `ip link show` and replace `interface` value in `nord-config` with the result.
- For 'battery', see the output of `ls -1 /sys/class/power_supply/` and copy the correct battery and adapter to `battery-bat` and `battery-adp` in 'nord-config'.
- For window restack, clear `wm-restack` in `nord-config` should work.

**Comment by Yucklys** [comment] 2020-09-17 07:37
And I suggest look into `nord-config` file. There is a list of all the modules and short descriptions. Some modules may not be useful in your case. You can change the modules there.
All the customizable settings are in `nord-config`, you can also adjust the appearance of modules there.

**Comment by F4zii** [comment] 2020-09-17 07:38
I am not using any tiling window manager as for now, so I will try the first solution while I will use one, and for the battery, Im not using a laptop so I might as well remove it

**Comment by F4zii** [comment] 2020-09-17 07:38
> And I suggest look into `nord-config` file. There is a list of all the modules and short descriptions. Some modules may not be useful in your case. You can change the modules there.
> All the customizable settings are in `nord-config`, you can also adjust the appearance of modules there.

alright, thanks!

**Comment by Yucklys** [comment] 2020-09-17 07:50
> I am not using any tiling window manager as for now, so I will try the first solution while I will use one, and for the battery, Im not using a laptop so I might as well remove it

You can check out `xworkspaces` and `xwindow` in polybar official wiki. These two should work as long as your wm is EWMH supported. However, a tiling window manager is the first choice.

**Comment by Yucklys** [comment] 2020-09-17 07:52
I am going to close this issue. You can post further question if you still can not launch the bar.

**Closed as completed by Yucklys** 2020-09-17 07:52 UTC
